### ISSUE TITLE
I ran into the following error:

### ISSUE THREAD

**Issue by leeyunhome** [sid0312/anpr_yolov5#1]
Hello,

I ran into the following error:

(yolov5_env) C:\Users\mhbang\GitHub\anpr_yolov5>python detect.py --source sample_cars/  --weights weights/last.pt --conf 0.4
Traceback (most recent call last):
  File "detect.py", line 3, in <module>
    from utils.datasets import *
  File "C:\Users\mhbang\GitHub\anpr_yolov5\utils\datasets.py", line 12, in <module>
    import torch
  File "C:\Users\mhbang\anaconda3\envs\yolov5_env\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\mhbang\anaconda3\envs\yolov5_env\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 지정된 모듈을 찾을 수 없습니다

What am I supposed to do?

Thank you.

**Comment by sid0312** [comment]
Hey,
There seems a missing dll file in your anaconda torch package. Fix up the
torch installation.
Regards,
Siddhant

**Comment by leeyunhome** [comment]
Thank you.
